spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 192.168.2.87:8847
      discovery:
        username: nacos
        namespace: public
        password: nacos
        # false为永久实例，true表示临时实例
        ephemeral: true
        # 命名空间
        group: DEFAULT_GROUP
        # false为永久实例，true表示临时实例
        service: ${spring.application.name:}
        weight: 1

server:
  port: 8001